import { Offer } from '../types/offer';

export const offers: Offer[] = [
  {
    id: 1,
    photo: [
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
    ],
    title: 'Beautiful & luxurious studio at great location',
    description: 'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
    premium: true,
    typeOfHousing: 'apartment',
    rating: 4.5,
    numberOfBedrooms: '3 Bedrooms',
    numberOfGuests: 'Max 4 adults',
    rentPerNight: 120,
    items: [{item: 'Wifi'}, {item: 'Heating'}, {item: 'Kitchen'}, {item: 'Cable TV'}],
    owner: {
      avatar: 'img/avatar-angelina.jpg',
      name: 'Angelina',
      pro: true,
    },
  },
  {
    id: 1,
    photo: [
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
    ],
    title: 'Beautiful & luxurious studio at great location',
    description: 'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
    premium: true,
    typeOfHousing: 'apartment',
    rating: 4.5,
    numberOfBedrooms: '3 Bedrooms',
    numberOfGuests: 'Max 4 adults',
    rentPerNight: 120,
    items: [{item: 'Wifi'}, {item: 'Heating'}, {item: 'Kitchen'}, {item: 'Cable TV'}],
    owner: {
      avatar: 'img/avatar-angelina.jpg',
      name: 'Angelina',
      pro: true,
    },
  },
  {
    id: 1,
    photo: [
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
    ],
    title: 'Beautiful & luxurious studio at great location',
    description: 'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
    premium: true,
    typeOfHousing: 'apartment',
    rating: 4.5,
    numberOfBedrooms: '3 Bedrooms',
    numberOfGuests: 'Max 4 adults',
    rentPerNight: 120,
    items: [{item: 'Wifi'}, {item: 'Heating'}, {item: 'Kitchen'}, {item: 'Cable TV'}],
    owner: {
      avatar: 'img/avatar-angelina.jpg',
      name: 'Angelina',
      pro: true,
    },
  },
  {
    id: 1,
    photo: [
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
      {src: 'img/apartment-small-04.jpg'},
    ],
    title: 'Beautiful & luxurious studio at great location',
    description: 'A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.',
    premium: true,
    typeOfHousing: 'apartment',
    rating: 4.5,
    numberOfBedrooms: '3 Bedrooms',
    numberOfGuests: 'Max 4 adults',
    rentPerNight: 120,
    items: [{item: 'Wifi'}, {item: 'Heating'}, {item: 'Kitchen'}, {item: 'Cable TV'}],
    owner: {
      avatar: 'img/avatar-angelina.jpg',
      name: 'Angelina',
      pro: true,
    },
  },
];
